name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  installation-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Obtém o código do repositório

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'      # Define a versão do Node.js necessária
        cache: 'npm'            # Habilita cache para dependências (npm)

      # INSTALAÇÃO DO ANGULAR
    - name: Install dependencies ng dependecies
      run: npm install
    
      # INSTALAÇÃO DO WS
    - name: Instalation of WS socket
      run: npm i
      working-directory: ./wssocket

    - name: Building WS socket
      run: npm run build
      working-directory: ./wssocket

      # INSTALAÇÃO DO FRONT-END
    - name: Preparing instalation of FrontEnd
      run: npm i
      working-directory: ./Front

    - name: Building FrontEnd
      run: npm run build
      working-directory: ./Front

      # INICIALIZANDO Websocket
    - name: initializing WS socket
      run: |
        cd ./wssocket &&
        npm start &

        cd ./Front &&
        npm start &

        sleep 30